### ISSUE TITLE
Need more microwaves

### ISSUE THREAD

**Issue by acabunoc** [acabunoc/github-playground#1]
Please purchase another microwave

🥘

**Comment by schae234** [comment]
What about a toaster oven?

**Comment by cs4allnyc** [comment]
@acabunoc we need one that's super fast!

**Comment by MakerTobey** [comment]
Hey, I can comment, too 👍

**Comment by acabunoc** [comment]
No to a toaster oven, because I want to microwave my plate

**Comment by acabunoc** [comment]
Agree, needs to be fast!

**Comment by acabunoc** [comment]
![](https://media.giphy.com/media/dy5pmvUvIdF1C/giphy.gif)

**Comment by MakerTobey** [comment]
Giff test ![](https://giphy.com/gifs/pasquale-psql-bee-11optsHvyEEJJC)

**Comment by cbaba20** [comment]
![alt text](https://giphy.com/gifs/lion-movie-lion-twc-3o6ZsXoYhtUlGEyIRa.gif)

**Comment by acabunoc** [comment]
Closing this issue since I don't want to buy a microwave
